use std::io::{BufRead, Write};
use nix::unistd::Uid;
mod all_dns;

fn main() {
    // Check user has linux root permission or not. If not, exit the program.
    if !Uid::effective().is_root() {
        println!("Please run as root!");
        std::process::exit(1);
    }

    let dns_list = all_dns::dns_loader::load_dns();


    // Show list DNS or find fastest DNS. (Ping test)
    println!("Do you want to find fastest DNS? (y/n)");
    let mut find_fastest = String::new();
    std::io::stdin()
        .read_line(&mut find_fastest)
        .expect("Failed to read line");
    let find_fastest = find_fastest.trim();
    if find_fastest == "y" {
        println!("Finding fastest DNS...");
        println!("\n");
        let mut fastest_dns = ("", "", "", "");
        let mut fastest_time = 1000000.0;



        run_loading("10");

        // ping test
        for dns in dns_list.iter() {
            let mut cmd = std::process::Command::new("ping");
            cmd.arg("-c");
            cmd.arg("1");
            cmd.arg("-W");
            cmd.arg("1");
            cmd.arg(dns.2);
            let output = cmd.output().expect("failed to execute process");
            let output = String::from_utf8_lossy(&output.stdout);
            let output = output.split("time=").collect::<Vec<&str>>();
            if output.len() > 1 {
                let output = output[1].split(" ").collect::<Vec<&str>>();
                let output = output[0].parse::<f32>().unwrap();
                if output < fastest_time {
                    fastest_time = output;
                    fastest_dns = *dns;
                }
            }
        }
        run_loading("50");
        run_loading("85");
        run_loading("100");




        println!("Fastest DNS is: {} - {} - {} - {} - {}ms", fastest_dns.0, fastest_dns.1, fastest_dns.2, fastest_dns.3, fastest_time);
        println!("Do you want to use this DNS? (y/n)");
        let mut use_fastest = String::new();
        std::io::stdin()
            .read_line(&mut use_fastest)
            .expect("Failed to read line");
        let use_fastest = use_fastest.trim();
        if use_fastest == "y" {
            // Export choosen dns
            let mut file = std::fs::File::create("./choosen_dns.txt").expect("create failed");
            file.write_all(b"# Generated by NetworkManager\n").expect("write failed");
            file.write_all(format!("nameserver {}\n", fastest_dns.2).as_bytes()).expect("write failed");
            file.write_all(format!("nameserver {}\n", fastest_dns.3).as_bytes()).expect("write failed");

            //set dns forever or only this session
            println!("Do you want to set DNS forever? (y/n)");
            let mut forever = String::new();
            std::io::stdin()
                .read_line(&mut forever)
                .expect("Failed to read line");
            let forever = forever.trim();
            if forever == "y" {
                // chattr -i /etc/resolv.conf
                let mut cmd = std::process::Command::new("chattr");
                cmd.arg("-i");
                cmd.arg("/etc/resolv.conf");
                let output = cmd.output().expect("failed to execute process");
                println!("{}", String::from_utf8_lossy(&output.stdout));
                println!("{}", String::from_utf8_lossy(&output.stderr));

                //export choosen dns
                let mut file = std::fs::File::create("./choosen_dns.txt").expect("create failed");
                file.write_all(b"# Generated by NetworkManager\n").expect("write failed");
                file.write_all(format!("nameserver {}\n", fastest_dns.2).as_bytes()).expect("write failed");
                file.write_all(format!("nameserver {}\n", fastest_dns.3).as_bytes()).expect("write failed");



                // change dns
                let mut cmd = std::process::Command::new("cp");
                cmd.arg("-r");
                cmd.arg("./choosen_dns.txt");
                cmd.arg("/etc/resolv.conf");
                let output = cmd.output().expect("failed to execute process");
                println!("{}", String::from_utf8_lossy(&output.stdout));
                println!("{}", String::from_utf8_lossy(&output.stderr));
                println!("DNS changed to {}", fastest_dns.1);

                // chattr +i /etc/resolv.conf
                let mut cmd = std::process::Command::new("chattr");
                cmd.arg("+i");
                cmd.arg("/etc/resolv.conf");
                let output = cmd.output().expect("failed to execute process");
                println!("{}", String::from_utf8_lossy(&output.stdout));
                println!("{}", String::from_utf8_lossy(&output.stderr));

                println!("Done!");
                println!("\n GitHub: Mohuva13");
            } else {
                // chattr -i /etc/resolv.conf
                let mut cmd = std::process::Command::new("chattr");
                cmd.arg("-i");
                cmd.arg("/etc/resolv.conf");
                let output = cmd.output().expect("failed to execute process");
                println!("{}", String::from_utf8_lossy(&output.stdout));
                println!("{}", String::from_utf8_lossy(&output.stderr));


                //export choosen dns
                let mut file = std::fs::File::create("./choosen_dns.txt").expect("create failed");
                file.write_all(b"# Generated by NetworkManager\n").expect("write failed");
                file.write_all(format!("nameserver {}\n", fastest_dns.2).as_bytes()).expect("write failed");
                file.write_all(format!("nameserver {}\n", fastest_dns.3).as_bytes()).expect("write failed");

                // change dns
                let mut cmd = std::process::Command::new("cp");
                cmd.arg("-r");
                cmd.arg("./choosen_dns.txt");
                cmd.arg("/etc/resolv.conf");
                let output = cmd.output().expect("failed to execute process");
                println!("{}", String::from_utf8_lossy(&output.stdout));
                println!("{}", String::from_utf8_lossy(&output.stderr));
                println!("DNS changed to {}", fastest_dns.1);

                println!("DNS will change to default after reboot!");
                println!("Done!");
                println!("\n GitHub: Mohuva13");
            }
        }
    }
    else {
        // Show the dns_list and user choose one of them

        println!("DNS List:");
        for (i, dns) in dns_list.iter().enumerate() {
            println!("{}. {} - {}", i, dns.0, dns.1);
        }
        println!("Choose one of them:");
        let mut dns_index = String::new();
        std::io::stdin()
            .read_line(&mut dns_index)
            .expect("Failed to read line");
        let dns_index: usize = dns_index.trim().parse().expect("Please type a number!");
        let dns = &dns_list[dns_index];
        println!("You choose: {}", dns.1);

        // Test ping of chosen dns
        println!("Do you want to test ping? (y/n)");
        let mut test_ping = String::new();
        std::io::stdin()
            .read_line(&mut test_ping)
            .expect("Failed to read line");
        let test_ping = test_ping.trim();
        if test_ping == "y" {
            // Test ping

            run_loading("40");

            let mut cmd = std::process::Command::new("ping");
            cmd.arg("-c");
            cmd.arg("5");
            cmd.arg(dns.2);
            let output = cmd.output().expect("failed to execute process");

            //Show ping result
            {
                let output = String::from_utf8_lossy(&output.stdout);
                let output = output.split("\n").collect::<Vec<&str>>();
                let output = output[output.len() - 2].split(" ").collect::<Vec<&str>>();
                let output = output[output.len() - 2].split("/").collect::<Vec<&str>>();
                run_loading("100");
                println!("Ping result:");
                println!("Min: {}ms", output[0]);
                println!("Max: {}ms", output[2]);
                println!("Average: {}ms", output[1]);
            }

            // Ask user set DNS or not
            println!("Do you want to set DNS? (y/n)");
            let mut set_dns = String::new();
            std::io::stdin()
                .read_line(&mut set_dns)
                .expect("Failed to read line");
            let set_dns = set_dns.trim();
            if set_dns == "n" {
                println!("Ok!");
                println!("\n GitHub: Mohuva13");
                return;
            }
        }


        // Export choosen dns
        let mut file = std::fs::File::create("./choosen_dns.txt").expect("create failed");
        file.write_all(b"# Generated by NetworkManager\n").expect("write failed");
        file.write_all(format!("nameserver {}\n", dns.2).as_bytes()).expect("write failed");
        file.write_all(format!("nameserver {}\n", dns.3).as_bytes()).expect("write failed");


        // chattr -i /etc/resolv.conf
        let mut cmd = std::process::Command::new("chattr");
        cmd.arg("-i");
        cmd.arg("/etc/resolv.conf");
        let output = cmd.output().expect("failed to execute process");
        println!("{}", String::from_utf8_lossy(&output.stdout));
        println!("{}", String::from_utf8_lossy(&output.stderr));

        // Choose set DNS forever or only for this session
        println!("Do you want to set DNS forever? (y/n)");
        let mut forever = String::new();
        std::io::stdin()
            .read_line(&mut forever)
            .expect("Failed to read line");
        let forever = forever.trim();



        // change dns
        let mut cmd = std::process::Command::new("cp");
        cmd.arg("-r");
        cmd.arg("./choosen_dns.txt");
        cmd.arg("/etc/resolv.conf");
        let output = cmd.output().expect("failed to execute process");
        println!("{}", String::from_utf8_lossy(&output.stdout));
        println!("{}", String::from_utf8_lossy(&output.stderr));
        println!("DNS changed to {}", dns.1);


        // chattr +i /etc/resolv.conf
        if forever == "y" {

            run_loading("100");


            // chattr +i /etc/resolv.conf
            let mut cmd = std::process::Command::new("chattr");
            cmd.arg("+i");
            cmd.arg("/etc/resolv.conf");
            let output = cmd.output().expect("failed to execute process");
            println!("{}", String::from_utf8_lossy(&output.stdout));
            println!("{}", String::from_utf8_lossy(&output.stderr));
        } else {
            run_loading("100");
            println!("DNS will change to default after reboot!");
        }
        println!("Done!");
        println!("\n GitHub: Mohuva13");
    }
}

fn run_loading(time: &str){
    std::process::Command::new("sh")
        .arg("./loading_.sh")
        .arg(time)
        .spawn().expect("");
}